# Generated by Django 3.1.3 on 2020-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('unit', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
    ]
